# Generated by Django 5.2 on 2026-03-20 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NutritionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe_name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="料理名"
                    ),
                ),
                (
                    "calories",
                    models.FloatField(
                        blank=True, null=True, verbose_name="カロリー(kcal/人)"
                    ),
                ),
                (
                    "protein",
                    models.FloatField(
                        blank=True, null=True, verbose_name="たんぱく質(g/人)"
                    ),
                ),
                (
                    "fat",
                    models.FloatField(blank=True, null=True, verbose_name="脂質(g/人)"),
                ),
                (
                    "carbs",
                    models.FloatField(
                        blank=True, null=True, verbose_name="炭水化物(g/人)"
                    ),
                ),
                (
                    "salt",
                    models.FloatField(blank=True, null=True, verbose_name="塩分(g/人)"),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, verbose_name="APIレスポンス"),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "nutrition_cache",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="料理名")),
                (
                    "genre1",
                    models.CharField(
                        choices=[
                            ("和食", "和食"),
                            ("洋食", "洋食"),
                            ("中華", "中華"),
                            ("スイーツ", "スイーツ"),
                        ],
                        max_length=20,
                        verbose_name="ジャンル1",
                    ),
                ),
                (
                    "genre2",
                    models.CharField(
                        choices=[
                            ("主食", "主食"),
                            ("主菜", "主菜"),
                            ("副菜", "副菜"),
                            ("汁物", "汁物"),
                        ],
                        max_length=20,
                        verbose_name="ジャンル2",
                    ),
                ),
                (
                    "genre3",
                    models.CharField(
                        blank=True,
                        choices=[("", "---"), ("肉系", "肉系"), ("魚系", "魚系")],
                        max_length=20,
                        verbose_name="ジャンル3",
                    ),
                ),
                ("servings", models.PositiveIntegerField(verbose_name="人数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recipe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="材料名")),
                (
                    "amount",
                    models.CharField(blank=True, max_length=50, verbose_name="分量"),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "ingredient",
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="順番")),
                ("description", models.TextField(verbose_name="手順")),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "step",
                "ordering": ["order"],
            },
        ),
    ]
