# Generated by Django 5.2 on 2026-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_ingredient_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="genre2",
            field=models.CharField(
                choices=[
                    ("主食", "主食"),
                    ("主菜", "主菜"),
                    ("副菜", "副菜"),
                    ("汁物", "汁物"),
                    ("その他", "その他"),
                ],
                max_length=20,
                verbose_name="ジャンル2",
            ),
        ),
    ]
