# Generated by Django 5.2 on 2026-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_remove_ingredient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
                verbose_name="数量",
            ),
        ),
    ]
