# Generated by Django 5.2 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_ingredient_quantity_decimal_places_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_simple",
            field=models.BooleanField(default=False, verbose_name="簡易献立"),
        ),
    ]
