# Generated by Django 5.2 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("recipes", "0009_alter_recipe_is_simple")]

    operations = [
        migrations.AddField(
            model_name="nutritioncache",
            name="fiber",
            field=models.FloatField(
                blank=True, null=True, verbose_name="食物繊維(g/人)"
            ),
        ),
        migrations.AddField(
            model_name="nutritioncache",
            name="vegetables_g",
            field=models.FloatField(blank=True, null=True, verbose_name="野菜量(g/人)"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="main_protein",
            field=models.CharField(
                blank=True,
                choices=[
                    ("鶏肉", "鶏肉"),
                    ("豚肉", "豚肉"),
                    ("牛肉", "牛肉"),
                    ("ひき肉", "ひき肉"),
                    ("魚", "魚"),
                    ("魚介その他", "魚介その他"),
                    ("豆腐・大豆", "豆腐・大豆"),
                    ("卵", "卵"),
                    ("なし", "なし"),
                ],
                max_length=20,
                verbose_name="主たんぱく源",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cooking_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("焼く", "焼く"),
                    ("炒める", "炒める"),
                    ("煮る", "煮る"),
                    ("揚げる", "揚げる"),
                    ("蒸す", "蒸す"),
                    ("茹でる", "茹でる"),
                    ("和える・生", "和える・生"),
                    ("汁物", "汁物"),
                    ("その他", "その他"),
                ],
                max_length=20,
                verbose_name="調理法",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="flavor_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("和風だし・醤油", "和風だし・醤油"),
                    ("味噌", "味噌"),
                    ("塩", "塩"),
                    ("甘辛", "甘辛"),
                    ("中華", "中華"),
                    ("カレー・スパイス", "カレー・スパイス"),
                    ("トマト", "トマト"),
                    ("クリーム・チーズ", "クリーム・チーズ"),
                    ("エスニック", "エスニック"),
                    ("その他", "その他"),
                ],
                max_length=20,
                verbose_name="味付け系統",
            ),
        ),
    ]
