# Generated by Django 5.2 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("recipes", "0008_recipe_is_simple")]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("ai_comment", models.TextField(blank=True, verbose_name="AIコメント")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meal_plan",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealPlanSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="順番")),
                ("days", models.PositiveIntegerField(verbose_name="日数")),
                ("is_free", models.BooleanField(default=False, verbose_name="自由枠")),
                (
                    "free_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="自由枠メモ"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="選定理由"
                    ),
                ),
                (
                    "main_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_plan_slots",
                        to="recipes.recipe",
                        verbose_name="主菜",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="planner.mealplan",
                    ),
                ),
                (
                    "side_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="side_plan_slots",
                        to="recipes.recipe",
                        verbose_name="副菜",
                    ),
                ),
            ],
            options={"db_table": "meal_plan_slot", "ordering": ["order"]},
        ),
        migrations.AddConstraint(
            model_name="mealplanslot",
            constraint=models.UniqueConstraint(
                fields=("plan", "order"), name="unique_plan_slot_order"
            ),
        ),
    ]
