# Generated by Django 5.2 on 2026-07-12

import django.core.validators
from django.db import migrations, models


def remove_free_slots(apps, schema_editor):
    meal_plan_slot = apps.get_model("planner", "MealPlanSlot")
    meal_plan_slot.objects.filter(is_free=True).delete()


class Migration(migrations.Migration):
    dependencies = [("planner", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="user_request",
            field=models.TextField(blank=True, verbose_name="要望"),
        ),
        migrations.RunPython(remove_free_slots, migrations.RunPython.noop),
        migrations.RemoveField(model_name="mealplanslot", name="free_text"),
        migrations.RemoveField(model_name="mealplanslot", name="is_free"),
        migrations.AlterField(
            model_name="mealplanslot",
            name="days",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="日数",
            ),
        ),
    ]
