# Generated by Django 5.2 on 2026-07-12

from datetime import timedelta

from django.db import migrations, models


def fill_slot_start_dates(apps, schema_editor):
    meal_plan = apps.get_model("planner", "MealPlan")
    for plan in meal_plan.objects.prefetch_related("slots"):
        current = plan.start_date
        for slot in plan.slots.all().order_by("order"):
            slot.start_date = current
            slot.save(update_fields=["start_date"])
            current += timedelta(days=slot.days)


class Migration(migrations.Migration):
    dependencies = [("planner", "0002_adjust_plan_composition")]

    operations = [
        migrations.AddField(
            model_name="mealplanslot",
            name="start_date",
            field=models.DateField(null=True, verbose_name="枠の開始日"),
        ),
        migrations.RunPython(fill_slot_start_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mealplanslot",
            name="start_date",
            field=models.DateField(verbose_name="枠の開始日"),
        ),
    ]
